# Generated by Django 3.2.7 on 2021-10-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers_data',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
