# Generated by Django 3.2.7 on 2021-10-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0002_sneakers_data_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='product_url',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='sku',
        ),
        migrations.AddField(
            model_name='sneakers_data',
            name='sku',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
