# Generated by Django 3.2.7 on 2021-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0003_auto_20211005_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='brand_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
