# Generated by Django 3.2.7 on 2021-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0004_alter_sneakers_data_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='release_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
