# Generated by Django 3.2.7 on 2021-10-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0005_alter_sneakers_data_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='brand_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='color',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='designer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='nick_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='product_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='product_type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='sku',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_name',
            field=models.CharField(max_length=50),
        ),
    ]
