# Generated by Django 3.2.7 on 2021-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0007_auto_20211005_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='product_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
