# Generated by Django 3.2.7 on 2021-10-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0009_auto_20211005_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='brand_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='color',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='description',
            field=models.TextField(default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='designer',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='material',
            field=models.TextField(default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='nick_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='product_id',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='product_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='product_placeholder',
            field=models.TextField(default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='product_type',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='sku',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='slug',
            field=models.TextField(default=None, max_length=2500, null=True),
        ),
    ]
