# Generated by Django 3.2.7 on 2021-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0011_auto_20211005_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='image',
            field=models.URLField(default=None, max_length=1000, null=True),
        ),
    ]
