# Generated by Django 3.2.7 on 2021-10-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0012_alter_sneakers_data_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers_data',
            name='average_price',
        ),
    ]
