# Generated by Django 3.2.7 on 2021-10-25 09:09

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0013_remove_sneakers_data_average_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers_data',
            name='average_price',
            field=computed_property.fields.ComputedCharField(compute_from='calculate_average', editable=False, max_length=10, null=True),
        ),
    ]
