# Generated by Django 3.2.7 on 2021-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0014_sneakers_data_average_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers_data',
            name='image',
        ),
        migrations.AddField(
            model_name='sneakers_data',
            name='images',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
