# Generated by Django 3.2.7 on 2021-10-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0015_auto_20211028_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers_data',
            name='category',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
