# Generated by Django 3.2.7 on 2021-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0016_sneakers_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
