# Generated by Django 3.2.7 on 2021-10-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0017_alter_sneakers_data_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers_data',
            name='product_id',
        ),
    ]
