# Generated by Django 3.2.7 on 2021-10-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0018_remove_sneakers_data_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers_data',
            name='low_price',
        ),
        migrations.AddField(
            model_name='sneakers_data',
            name='lowest_price',
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='highest_price',
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
    ]
