# Generated by Django 3.2.7 on 2021-10-31 09:03

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0019_auto_20211031_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='average_price',
            field=computed_property.fields.ComputedCharField(compute_from='calculate_average', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='highest_price',
            field=models.FloatField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sneakers_data',
            name='lowest_price',
            field=models.FloatField(default=None, max_length=100, null=True),
        ),
    ]
