# Generated by Django 3.2.7 on 2021-10-31 09:20

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0020_auto_20211031_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers_data',
            name='average_price',
            field=computed_property.fields.ComputedFloatField(compute_from='calculate_average', editable=False, max_length=100, null=True),
        ),
    ]
