# Generated by Django 3.2.7 on 2021-11-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaerksdata', '0021_alter_sneakers_data_average_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='vendor_url',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
    ]
